### PR TITLE
Add support for DB-IP.com geocoding service, take 2

### PR DESCRIPTION
**Pull request by cv**
This PR is a continuation of https://github.com/alexreisner/geocoder/pull/1063, which seems to have been abandoned in 2016, and I'd like to help see it through to a release.

### CODE REVIEW

**Comment by cv** [comment]
@TrangPham can you confirm that the changes from aed0040 where what you expected from your comment in https://github.com/alexreisner/geocoder/pull/1063#r68345935?

**Comment by TrangPham** [comment]
@cv THANKS!

Yes this is what I meant by that comment.

**Comment by cv** [comment]
@TrangPham excellent - do you update the changelog, or should I add another commit for that?

**Comment by TrangPham** [comment]
@alexreisner Usually does this when he cuts newer versions

**Comment by cv** [comment]
Ah, thanks for clarifying. Sounds great, and I'm looking forward to it :)

**Pull request merged**
