### PR TITLE
add bounds detection for google results

### PR DESCRIPTION
**Pull request by jormon**
some google geocoding requests have bounds within the result.  add a
helper to extract these.

### CODE REVIEW

**Comment by TrangPham** [comment]
Hi thanks for the PR! You said 'some' of the responses have it. Could you
also ensure that there's a test cause for when the response doesn't have it?

**Comment by jormon** [comment]
@TrangPham thanks for the thoughts re: testing -- I added that test case.  Note that this required a slight code change too since we now want divergent behavior from `#viewport` when there is no data.

**Comment by alexreisner** [comment]
@jormon thanks for this, and for adding the test.

For anyone who (in addition to me) is baffled by the difference between "bounds" and "viewport," it's explained in Google's docs: https://developers.google.com/maps/documentation/geocoding/intro#Results

**Comment by jormon** [comment]
@TrangPham will this get merged?

**Comment by alexreisner** [comment]
@jormon sorry for the delay, and thanks!

**Pull request merged**
