### PR TITLE
[db-ip] Handle Geocoder::OverQueryLimitError gracefully

### PR DESCRIPTION
**Pull request by cv**
`Geocoder::OverQueryLimitError` errors were not being generated correctly, and the response was coming back empty but with no indication.

### CODE REVIEW

**Comment by TrangPham** [comment]
Looks good to me - could you add another test case and fixture for it, similar to: https://github.com/alexreisner/geocoder/blob/master/test/fixtures/db_ip_com_invalid_key

Thanks!

**Comment by cv** [comment]
Thanks for having a look at this @TrangPham! I've added the fixture file, but not quite sure how it gets picked up by the tests. Got a pointer?

**Comment by TrangPham** [comment]
@cv Thanks for your quick response :)

Here's an example: https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/test/unit/lookups/geocodio_test.rb#L63-L67

**Comment by cv** [comment]
Looks like there's an unrelated CI failure with jruby 1.9, but other than that all tests are passing now! :)

**Comment by TrangPham** [comment]
Thanks! Looks like the error is unrelated :)

**Pull request merged**
