### PR TITLE
yandex bbox support

### PR DESCRIPTION
**Pull request by unloved**

### CODE REVIEW

**Comment by alexreisner** [comment]
Thanks! This looks good, but I think the param should be called `bounds`, instead of `bbox`, for consistency with Google and Opencagedata lookups. (Obviously the query string remains `bbox`.) Would you mind changing that?

**Comment by unloved** [comment]
@alexreisner i've updated pr

**Comment by TrangPham** [comment]
Looks like this PR caused a unit test failure: 
https://travis-ci.org/alexreisner/geocoder/jobs/299808592
``` 
Failure:
  </bbox=40.0+%2C-120.0+%7E39.0+%2C-121.0+/> was expected to be =~
  <"https://maps.googleapis.com/maps/api/geocode/json?address=Some+Intersection&bounds=40.000000%2C-120.000000%7C39.000000%2C-121.000000&key=%5B%22auti-id%22%2C+%22auth-token%22%5D&language=en&sensor=false">.
test_yandex_query_url_contains_bbox(YandexTest)
/home/travis/build/alexreisner/geocoder/test/unit/lookups/yandex_test.rb:29:in `test_yandex_query_url_contains_bbox'
E
===============================================================================
Error: test_yandex_query_url_contains_bbox(YandexTest): Encoding::ConverterNotFoundError: code converter not found (UTF-8 to UTF-8)
```

**Comment by alexreisner** [comment]
Good catch @TrangPham! Just fixed this in d6a7b65cbed4412ec891cf1f718eff21f9a1ed8d.

**Pull request merged**
