### PR TITLE
handles unreachable network exception

### LINKED ISSUE #1019: Exception Errno::ENETUNREACH isn't handled
Hey. I've error like this using geocoder 1.2.14
```
Errno::ENETUNREACH: Network is unreachable - connect(2) for "freegeoip.net" port 80
  from net/http.rb:879:in `initialize'
  from net/http.rb:879:in `open'
  from net/http.rb:879:in `block in connect'
  from timeout.rb:88:in `block in timeout'
  from timeout.rb:98:in `call'
  from timeout.rb:98:in `timeout'
  from net/http.rb:878:in `connect'
  from net/http.rb:863:in `do_start'
  from net/http.rb:852:in `start'
  from net/http.rb:583:in `start'
  from geocoder/lookups/base.rb:276:in `make_api_request'
  from geocoder/lookups/base.rb:226:in `fetch_raw_data'
  from geocoder/lookups/base.rb:177:in `fetch_data'
  from geocoder/lookups/freegeoip.rb:25:in `results'
  from geocoder/lookups/base.rb:47:in `search'
  from geocoder/query.rb:11:in `execute'
  from geocoder.rb:22:in `search'
  from geocoder/request.rb:9:in `location'
```

In `lib/geocoder/lookups/base.rb:273` there's make_api_requests
image
Seems like you are rescuing only `Timeout::Error`

Do you acknowledge this as bug? Or it's supposed to be like that?
I can provide PR that fixes it but need some guidance how you would like it to be handled.

### PR DESCRIPTION
**Pull request by sas1ni69**
resolves #1019

### CODE REVIEW

**Comment by TrangPham** [comment]
Hi @sas1ni69 

You'll need to add the NetworkError to this file: https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/exceptions.rb
Could you add a unit test?

Thank you for the pull request :)

**Comment by sas1ni69** [comment]
Hey @TrangPham thanks for the feedback, I'll update the PR :)

**Comment by sas1ni69** [comment]
@TrangPham updated. Please let me know if you'd like me to add or change anything. Really appreciate you taking the time to look into this.

**Comment by TrangPham** [comment]
Sorry I've taken a while to get back to you!

:D It looks good

**Comment by sas1ni69** [comment]
No worries I know you're busy. Thanks for merging it! 💃

**Pull request merged**
