### PR TITLE
Added PickPoint provider.

### PR DESCRIPTION
**Pull request by cylon-v**

### CODE REVIEW

**Comment by TrangPham** [comment]
Hi I am confused at why you're reusing the Nominatim lookup for this. Unless there is a specific association between pick point and nominatim, even though they might currently share a lot of the same format, I think you should be inheriting from the base lookup and base result instead. 

Thanks for this PR! :)

**Comment by cylon-v** [comment]
Hi @TrangPham, PickPoint is a commercial service based on Nominatim. Basically it's exactly the same but has minor differences, i.e. in URL format.

**Comment by TrangPham** [comment]
I can't find the documentation on the PickPoint site which says that. I'm okay with inheriting from nominatim if we know for sure that's what they are relaying on.

**Comment by cylon-v** [comment]
I'm PickPoint developer :).

**Comment by TrangPham** [comment]
:D Okay! thanks

**Comment by cylon-v** [comment]
Thank you!

**Pull request merged**
