### PR TITLE
Force specfify ip_lookup on search, even when ip_address? fails

### PR DESCRIPTION
**Pull request by TrangPham**
Connected to #776

### CODE REVIEW

**Comment by alexreisner** [comment]
Thanks for tackling this problem. I like the simplicity of this solution, but I think it should be even simpler. The issue is that we eventually want to be able to configure multiple lookups (see #351 and #746) and that configuration should be kept to the `Geocoder.configure` method. Even regardless of that, we shouldn't need to re-specify our IP lookup when all we really want is to be able to force a particular bit of input to be treated as an IP address. Right? What if we just check for the truthiness of `options[:ip_address]`? I also think that should be checked before the `ip_address?` method is run, as checking the hash value is a faster operation than running the method.

**Comment by TrangPham** [comment]
@alexreisner Thanks I've made the changes that you suggested.

**Comment by alexreisner** [comment]
Thanks! Also, I realized after I merged that you can use more specific assertions in your tests. See e065f6de.

**Comment by TrangPham** [comment]
@alexreisner Thanks

The same change from assert_equal  to assert_instance_of can also be made to `query_test.rb` line 50, and in `geocoder_test.rb` line 64, 70, 76 for consistency

**Comment by alexreisner** [comment]
Good eye!

**Comment by mmzoo** [comment]
Sweet! Thank you very much.

**Pull request merged**
