### PR TITLE
Use a proper domain name in ipapi_com lookup

### PR DESCRIPTION
**Pull request by piotrgorecki**
I omitted that I should use different domain name in case when an api key is in use.
Moreover, when the api key is invalid, the service respond "invalid key" - should I handle this?

My original pull request: [https://github.com/alexreisner/geocoder/pull/1018](https://github.com/alexreisner/geocoder/pull/1018)

### CODE REVIEW

**Comment by TrangPham** [comment]
Yes - the invalid key can be handled in the result method of the lookup

**Comment by piotrgorecki** [comment]
I handle it in parse_raw_data, because the service's response is the plain text "invalid key\n", not any json.

**Comment by TrangPham** [comment]
@piotrgorecki 

For other invalid keys in geocoder, we use
```
          raise_error(Geocoder::InvalidApiKey) || Geocoder.log(:warn, "Invalid API key.")
```

Could you use this for the invalid key to make it uniform with the other geocoder lookups? This will help geocoder users catch the error.

**Comment by TrangPham** [comment]
Thanks so much @piotrgorecki 👍 Looks like people have already started using your new addition!

**Pull request merged**
