### PR TITLE
Google Places Search Lookup

### PR DESCRIPTION
**Pull request by waruboy**
Hello. This is my attempt to integrate gogole places search lookup, as discussed on https://github.com/alexreisner/geocoder/issues/1128 . 

This query return way less data than other google query though, so many method will just return blank.
What do you think?

### CODE REVIEW

**Comment by waruboy** [comment]
Hmm, I have no idea why the rbx based CI test is failing. Something about the gemset which I don't touch

**Comment by alexreisner** [comment]
Ah, sorry, don't worry about that failing test. Nothing to do with what you did, which looks great! I just need to find the time to go over it more carefully--at the moment the only thing I can spot that's missing is an entry in the README.

**Comment by waruboy** [comment]
@alexreisner Thanks for responding! No pressure from here, I know it can be though maintaining an OSS project. Ah yes, will draft something to add in the README

**Comment by alexreisner** [comment]
Looks good. One more thing: is it necessary to define the `results` method in the lookup? It looks the same as the method in the lookup it's inheriting from, but maybe I'm missing something subtle...

**Comment by waruboy** [comment]
@alexreisner Ah yeah, only different is just the log message when raising error.
I followed the style of GooglePlaceDetails lookup

**Comment by alexreisner** [comment]
Ah, right. In that case I think it'd be better to make the superclass's method insert the name of the lookup dynamically into the error message. There's too much critical functionality in there to copy and paste. It will have the side effect of slightly improving the Google Premier lookup's error message, too.

**Comment by waruboy** [comment]
@alexreisner good idea. Should we make it another PR or just merge it here? Would be happy to do either way

**Comment by alexreisner** [comment]
Here is good. Thanks!

**Comment by waruboy** [comment]
@alexreisner done!

**Comment by alexreisner** [comment]
Ah, sorry, I should have been more specific. Just call the `name` method on the lookup for the human-readable name that should go in the error message. That make sense?

**Comment by waruboy** [comment]
@alexreisner  woops, totally forgot that we have that method. Is this what you mean?

**Comment by aceunreal** [comment]
Is it worth also adding a `google_premier_places_search` lookup?

**Comment by waruboy** [comment]
@aceunreal I don't know. Does it need different request? The premium data feature will be deprecated though
https://developers.google.com/places/web-service/search#premium-data

**Comment by aceunreal** [comment]
@waruboy when using a Google premium plan, you have the possibility of using a signature as the authentication. eg: https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/google_premier.rb

Premium data is different from premium plan and I do not believe these will be deprecated anytime soon.

**Comment by waruboy** [comment]
@aceunreal Ah, I think it is not applicable for google places.
From: https://developers.google.com/places/web-service/search

> Note for Google Maps APIs Premium Plan customers: You must include an API key in your requests. You should not include a client or signature parameter with your requests.

Or is this different with what you are talking?

**Comment by aceunreal** [comment]
@waruboy 👍  Looks like client/signature is not supported for Google places

**Comment by waruboy** [comment]
Thanks :smile:

**Pull request merged**
