### PR TITLE
Add locale support to GeoIP2 result display class

### PR DESCRIPTION
**Pull request by davydovanton**
:cat:

### CODE REVIEW

**Comment by alexreisner** [comment]
Thanks! This is good, but could you add a test?

**Comment by davydovanton** [comment]
@alexreisner hello, sorry, I hadn't time for this PR. I add test case for checking locale :smile:

**Comment by alexreisner** [comment]
OK, thanks! A few things:

1. Take a look at the test failures on Travis. I think you just need to add `# encoding: utf-8` to the top of `test/test_helper.rb`.
2. Instead of `Geocoder.config[:language]`, please use `configuration[:language]` instead, which will return language for the specific lookup you're in.
3. In the test you added, if it fails the final line (which sets the language back to English) will not be executed. I think you need an `ensure`.

**Comment by davydovanton** [comment]
@alexreisner thanks for feedback!
1. Yes, I loosed this, thanks for catch!
3. Instead `ensure` I use the `teardown` callback :smiley:

**Comment by davydovanton** [comment]
all tests passed :blush:

**Comment by alexreisner** [comment]
Looks good. Thanks!

**Comment by davydovanton** [comment]
Thanks for merge and review! :tada:

**Pull request merged**
