### PR TITLE
Include in ActionDispatch::Request instead of Rack:Request, closes #966

### LINKED ISSUE #966: Issue with Rails 5 beta - Geocoder::Request can't be initialized
I just upgraded my app to Rails 5 beta and it seems that Geocoder::Request can't be initialized, hence request.location (using in my View) returned this 

"undefined method `location' for #<ActionDispatch::Request:0x007f91127f3280>"

Can someone help me with this ? Tks

### PR DESCRIPTION
**Pull request by alepore**
see https://github.com/alexreisner/geocoder/issues/966#issuecomment-176004476

### CODE REVIEW

**Comment by TrangPham** [comment]
Thanks @alepore!

**Comment by alexreisner** [comment]
See #1060. I think we still need to look for/include in `Rack::Request`, if `ActionDispatch::Request` is not defined.

**Comment by alexreisner** [comment]
@alepore @TrangPham could you take a quick look at #1066? Why is it failing for him while it's working for others?

**Comment by alepore** [comment]
@alexreisner 👍 replied, it's public for some years...

**Pull request merged**
