### PR TITLE
I believe this might be a leftover from development that someone forg…

### PR DESCRIPTION
**Pull request by LukeLaupheimer**
…ot to delete. Reject if I'm incorrect.

### CODE REVIEW

**Comment by alexreisner** [comment]
Nope, it's intentional: c557ba436eadf750aa609bcef0010ca91d0f8f25. Requested feature.

**Comment by LukeLaupheimer** [comment]
That's fine, but this thing dumps text right in the middle of my rspec tests. Example:

```
++ bundle exec rspec spec /Users/enablelabs/.rvm/gems/ruby-2.2.1@mori_pages/gems/respec-0.8.3/lib/respec/formatter.rb

Randomized with seed 63352
...........................................................................................................................................Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=415+River+Street%2C+Troy%2C+NY%2C+12180&language=en&sensor=false
...............................................................................................Geocoder: HTTP request being made for http://maps.googleapis.com/maps/api/geocode/json?address=415+River+Street%2C+Troy%2C+NY%2C+12180&language=en&sensor=false
..............................................................................

Finished in 4 minutes 21 seconds (files took 3.06 seconds to load)
312 examples, 0 failures
```

It's not like the gem is broken, but I will say this is annoying.

**Comment by alexreisner** [comment]
Should only be appearing if log level is `:debug`, no?

**Comment by LukeLaupheimer** [comment]
Nope, it goes direct to puts:
```ruby
# /lib/geocoder/logger.rb

# Line 38
def kernel_log(level, message)
  case level
  when :debug, :info
    puts message
```

**Comment by alexreisner** [comment]
I think the correct solution to this is for the "kernel" logger to have a configurable level (default: `:warn`). I'd rather add that than remove the request URL logging, which is useful. (cc: @TrangPham)

**Comment by LukeLaupheimer** [comment]
I mean, I suppose it could be arguably useful in some context maybe, but it's definitely not useful in mine. In fact, it's actively causing a problem. Normal use of a gem like this absolutely should not be outputting directly to `stdout`.

**Comment by alexreisner** [comment]
Yes, it's useful. See #678. It's just shouldn't be on by default. Will fix soon (see #881).

**Pull request closed without merging**
