### PR TITLE
Fix Geocoder::Result::Yandex data extraction

### PR DESCRIPTION
**Pull request by iarie**
Hello Geocoders! 
I found a nasty bug that prevents me from extract address data on deeply nested Russian addresses.
Additionally i removed `#premise_name` because it targeting non existing JSON key/node and also added `postal_code` extraction.

Tested on many worldwide locations.

### CODE REVIEW

**Comment by alexreisner** [comment]
Thanks! This looks good. Just a couple of issues:

1. What makes the Yandex lookup difficult to maintain is that it seems to return different data structures for different queries, and I can't tell from the docs (I don't know Russian) when changes are universal or query-specific. For example, we have a test fixture that *does* have a `PremiseName` key, so I'm nervous to get rid of that method.
2. I want to make sure there are no exceptions, esp when the data structure is so inconsistent. Can we check whether keys refer to hashes, not just whether they exist? Eg: `if thoroughfare_data.is_a?(Hash)`

**Comment by iarie** [comment]
Hello, @alexreisner, i found that PremiseName is completly legit field, and I ended up rewriting YandexResult class, take a look: 
i introduce `dig` method emulation with hash checkings, and common data stucture patterns as constants.
The way i tested: fire geocoder to different cases  and check Yandex::Result public interface 
Runned cases:
```ruby
Geocoder.configure(lookup: :yandex)

addresses = [
"Paris, Etienne Marcel 17",
"Saint Petersbourg, Griboedova 14",
"Boris Nemtsov plaza, Washington DC",
"Berlin, Tempelhofer Damm, 3",
"Lyon, Cours Suchet 42",
"Trabzon, Kanuni Ortaokulu",
"Upper New York Bay, NY",
"Potomak",
"Volga river",
"Baltic sea"]
fields = [:coordinates, :address, :city, :country, :country_code, :state, :sub_state, :state_code, :street, :street_number, :premise_name, :postal_code, :kind, :precision, :viewport]
addresses.map do |address|
  geo = Geocoder.search(address).first
  [address, fields.each_with_object({}) { |f, obj| obj[f] = geo.send(f) }]
end.to_h

```
results:
```ruby
{
  "Paris, Etienne Marcel 17" => {
    :coordinates => [48.863657, 2.349418],
    :address => "France, Île-de-France, Paris, 1er Arrondissement, Rue Étienne Marcel, 17",
    :city => "Paris",
    :country => "France",
    :country_code => "FR",
    :state => "Île-de-France",
    :sub_state => "",
    :state_code => "",
    :street => "Rue Étienne Marcel",
    :street_number => "17",
    :premise_name => "",
    :postal_code => "",
    :kind => "house",
    :precision => "exact",
    :viewport => [48.860948, 2.345313, 48.866365, 2.353523]
  }, "Saint Petersbourg, Griboedova 14" => {
    :coordinates => [59.936034, 30.327286],
    :address => "Russia, Saint Petersburg, Kanala Griboedova Embankment, 14",
    :city => "Saint Petersburg",
    :country => "Russia",
    :country_code => "RU",
    :state => "Saint Petersburg",
    :sub_state => "",
    :state_code => "",
    :street => "Kanala Griboedova Embankment",
    :street_number => "14",
    :premise_name => "",
    :postal_code => "191186",
    :kind => "house",
    :precision => "exact",
    :viewport => [59.933974, 30.32318, 59.938094, 30.331391]
  }, "Boris Nemtsov plaza, Washington DC" => {: coordinates => [38.923825, -77.073529],
    :address => "United States of America, District of Columbia, City of Washington, Boris Nemtsov Plaza",
    :city => "City of Washington",
    :country => "United States of America",
    :country_code => "US",
    :state => "District of Columbia",
    :sub_state => "",
    :state_code => "",
    :street => "Boris Nemtsov Plaza",
    :street_number => "",
    :premise_name => "",
    :postal_code => "",
    :kind => "street",
    :precision => "street",
    :viewport => [38.923271, -77.073897, 38.92438, -77.073143]
  }, "Berlin, Tempelhofer Damm, 3" => {
    :coordinates => [52.482417, 13.386533],
    :address => "Germany, Berlin, Tempelhofer Damm, 3",
    :city => "Berlin",
    :country => "Germany",
    :country_code => "DE",
    :state => "Berlin",
    :sub_state => "Berlin",
    :state_code => "",
    :street => "Tempelhofer Damm",
    :street_number => "3",
    :premise_name => "",
    :postal_code => "",
    :kind => "house",
    :precision => "exact",
    :viewport => [52.47991, 13.382427, 52.484923, 13.390638]
  }, "Lyon, Cours Suchet 42" => {
    :coordinates => [45.746509, 4.824833],
    :address => "France, Auvergne-Rhône-Alpes, Rhône, Lyon, Cours Suchet, 42",
    :city => "Lyon",
    :country => "France",
    :country_code => "FR",
    :state => "Auvergne-Rhône-Alpes",
    :sub_state => "Rhône",
    :state_code => "",
    :street => "Cours Suchet",
    :street_number => "42",
    :premise_name => "",
    :postal_code => "",
    :kind => "house",
    :precision => "exact",
    :viewport => [45.743634, 4.820728, 45.749383, 4.828939]
  }, "Trabzon, Kanuni Ortaokulu" => {
    :coordinates => [40.983681, 39.779934],
    :address => "Republic of Turkey, Trabzon, Ortahisar, Kanuni Mah.",
    :city => "",
    :country => "Republic of Turkey",
    :country_code => "TR",
    :state => "Trabzon",
    :sub_state => "Ortahisar",
    :state_code => "",
    :street => "",
    :street_number => "",
    :premise_name => "",
    :postal_code => "",
    :kind => "district",
    :precision => "other",
    :viewport => [40.974334, 39.771849, 40.988256, 39.783294]
  }, "Upper New York Bay, NY" => {
    :coordinates => [40.621717, -73.835336],
    :address => "United States of America, New York, New York County, New York, Jamaica Bay",
    :city => "New York",
    :country => "United States of America",
    :country_code => "US",
    :state => "New York",
    :sub_state => "New York County",
    :state_code => "",
    :street => "",
    :street_number => "",
    :premise_name => "Jamaica Bay",
    :postal_code => "",
    :kind => "hydro",
    :precision => "other",
    :viewport => [40.568422, -73.896394, 40.649372, -73.768834]
  }, "Potomak" => {
    :coordinates => [39.334893, -77.758081],
    :address => "United States of America, Potomac River",
    :city => "",
    :country => "United States of America",
    :country_code => "US",
    :state => "",
    :sub_state => "",
    :state_code => "",
    :street => "",
    :street_number => "",
    :premise_name => "Potomac River",
    :postal_code => "",
    :kind => "hydro",
    :precision => "other",
    :viewport => [38.802449, -78.657888, 39.697393, -76.989887]
  }, "Volga river" => {
    :coordinates => [49.550996, 45.139984],
    :address => "Russia, Volga River",
    :city => "",
    :country => "Russia",
    :country_code => "RU",
    :state => "",
    :sub_state => "",
    :state_code => "",
    :street => "",
    :street_number => "",
    :premise_name => "Volga River",
    :postal_code => "",
    :kind => "hydro",
    :precision => "other",
    :viewport => [45.697053, 32.468241, 58.194645, 50.181608]
  }, "Baltic sea" => {
    :coordinates => [59.123074, 20.14896],
    :address => "Baltic Sea",
    :city => "",
    :country => "",
    :country_code => "",
    :state => "",
    :sub_state => "",
    :state_code => "",
    :street => "",
    :street_number => "",
    :premise_name => "Baltic Sea",
    :postal_code => "",
    :kind => "hydro",
    :precision => "other",
    :viewport => [53.593896, 12.010395, 65.914058, 30.237607]
  }
}
```
PS: i couldn't reporduce this test case on current master to see difference, it seems bugged on several conditions.
Should we write some new tests based on this data?

**Comment by iarie** [comment]
@alexreisner any updates with this PR?

**Comment by alexreisner** [comment]
Sorry for the delay. Reasons this is hard to evaluate:

1. Big PR that basically rewrites the whole lookup.
2. Lack of readable (ie, English) documentation (from Yandex) by which I can confirm that this new design makes sense.

I like what you're doing! It's cleaner and more explicit than what we've got currently. I just need to feel confident that it's a good model of what Yandex returns. Your examples (above) are excellent. As you suggest, yes, it would be great to add fixtures with the exact Yandex JSON responses for a few of those, and tests which use them? We don't necessarily need all of them, but a few that provide a variety of detail (eg, from "Volga river" to exact street addresses) would give me a lot more confidence.

As for the code, it's mostly merge-able quality, but a few remarks:

* It would be helpful to have a comment at the top explaining what the constants are (and that Yandex returns different data structures for different queries and it's not always possible to know in advance what you're going to get).
* It'd be good to show, maybe in a test, that the recursion in `dig_data` can't go on forever.

Sorry again for the delay. Thanks for the good work, and patience.

**Comment by iarie** [comment]
@alexreisner, I finally managed to update this, could you please take a look: I didn't find any reasonable API documentation and wrote descriptions with examples and tests.

**Comment by stereodenis** [comment]
@alexreisner @iarie any updates on it?

**Comment by alexreisner** [comment]
This has been merged (though Github doesn't indicate it). Sorry for the delay @iarie.

**Pull request closed without merging**
