### PR TITLE
Added locationiq provider

### PR DESCRIPTION
**Pull request by aleemuddin13**
Add support for LocationIQ #1070 

I don't know how to write tests. I would appreciate if any one help me out.

### CODE REVIEW

**Comment by TrangPham** [comment]
Hi @aleemuddin13 

Since your API is similar, you can use this to base your test file off of: https://github.com/alexreisner/geocoder/blob/master/test/unit/lookups/nominatim_test.rb

There are also some tests which you will have to modify. You can look at the travis failures to see which tests need to be fixed. This is because some of the tests loop through all the different lookups. 

To run the tests locally with default environment variables you can run `rake test` in your terminal. Travis would run the entire test suite for you with the different environment variables, so you'll want to make sure that all the travis tests are also passing after you have fixed the local tests. 

Please reach out if you have more specific questions or are blocked.
Thanks!

**Comment by aleemuddin13** [comment]
Thanks to @glsignal, tests are done.

**Comment by aleemuddin13** [comment]
@alexreisner, naming conventions updated.

**Comment by alexreisner** [comment]
Looks great, thanks!

**Comment by jgdreyes** [comment]
@alexreisner When do you think you will push out a new release with this change?

**Pull request merged**
