### PR TITLE
Updated Bing offering

### PR DESCRIPTION
**Pull request by guymorita**
Bing stats are outdated. They changed the offering sadly.

### CODE REVIEW

**Comment by alexreisner** [comment]
Thanks! This is good, but can we use the "Compare plans" URL for "Key signup" instead?

**Comment by guymorita** [comment]
they're a bit different. compare plans leads to key signup though.

**Comment by alexreisner** [comment]
Yes, but every other entry in the README has "Key signup" and the address currently given there for Bing is out of date.

**Comment by guymorita** [comment]
@alexreisner gotcha. updated the readme and replaced the old link. new link allows the user to compare plans first before signing up.

**Pull request merged**
