### PR TITLE
Add support for Ipregistry

### PR DESCRIPTION
**Pull request by lpellegr**
We have users who would like to use your great Ruby library with [Ipregistry](https://ipregistry.co). This PR adds support for this new service that is reliable and returns responses with very low latency worldwide.

### CODE REVIEW

**Comment by lpellegr** [comment]
Some test jobs are failing but failures are not related to the changes introduced by this PR. The failures look similar to the ones currently on the master.

**Comment by jmarbach** [comment]
Really thrilled to see this! Ipregistry offers much needed supplemental context that is useful for a wide range of use cases.

**Comment by lpellegr** [comment]
@alexreisner Is this repository still maintained?

**Comment by lpellegr** [comment]
@alexreisner Thanks for your answer and the review.

> in lookups/ipregistry.rb: If the only valid host is api.ipregistry.co, we should not look at a user-configured value for :host.

For some users, we provide a docker image they deploy by themselves. In that case, they need to specify their own value. Your comment let me noticed I missed HTTP as a supported protocol. I have added it to the list of supported protocols.

> in results/ipregistry.rb: What's the purpose of flattening the hash? Why not use the accessor methods to locate the data in the structure?

It prevents several `nil` checks and touching existing tests. Furthermore, it looks like existing integrations use a flat hierarchy so it's a way to keep this uniform.

> in README_API_GUIDE.md: Please insert the new lookup at the bottom of the list, rather than at the top.

Done.

**Comment by alexreisner** [comment]
OK, thanks. Merging.

**Comment by lpellegr** [comment]
@alexreisner Thanks! Is there any plan for a release soon?

**Comment by alexreisner** [comment]
Yes, probably this month.

**Pull request merged**
