### PR TITLE
fix reversing coordinates

### PR DESCRIPTION
**Pull request by arturictus**

### CODE REVIEW

**Comment by arturictus** [comment]
Linked to #886

**Comment by arturictus** [comment]
Added support for mongoid-geospacial gem.

**Comment by alexreisner** [comment]
Thanks for this, and sorry for the very delayed response. This seems reasonable but we need a test or two showing that it works as expected.

**Comment by alexreisner** [comment]
Closing, because while I like the idea of this, I think in an effort to simplify it may actually do the opposite. Generally I'm leaning towards reducing Geocoder's interaction with Mongo queries and data (since Mongo has its own way of doing geospatial operations).

**Pull request closed without merging**
