### PR TITLE
Abstract API

### PR DESCRIPTION
**Pull request by randoum**
Integration of one of my favorite API in one of my favorite Gems :)

BTW, after this PR, I am thinking of integrating a linter like Rubocop in Geocoder. What do you say?

### CODE REVIEW

**Comment by alexreisner** [comment]
Exemplary PR for a nice API. Thanks!

I'm responding about Rubocop in #1496.

**Comment by randoum** [comment]
Hey @alexreisner I was wondering about your plans for publishing the next version of Geocoder. Any estimated target date?
Cheers ;)

**Comment by alexreisner** [comment]
Just released!

**Comment by randoum** [comment]
:yellow_heart:

**Pull request merged**
