### PR TITLE
Add county accessor for map quest results

### PR DESCRIPTION
**Pull request by Devetzis**
Trivial change to expose the County in the mapquests results. 

Test cases run and I've tested the gem in my own application.

### CODE REVIEW

**Comment by alexreisner** [comment]
The problem with this is that counties don't exist in all (most?) countries. (For discussion see #739, #362.)

**Comment by Devetzis** [comment]
Alex:

I’ve read the referenced documents and I  don’t disagree, however: county is currently available for nominatim and opencagedata and sub_state is available from google and all are exposed by geocoder.

Additionally the map quest api http://open.mapquestapi.com/geocoding/ <http://open.mapquestapi.com/geocoding/> describes adminArea4 as County name and I’ve tested different locations and I get valid results (at least where I’ve checked).

So I understand your concern, but isn’t this also an issue for the geocode services I mentioned above?

Thanks…….

Perry Devetzis
Partner
Athena Technologies Corp.
perryd@athenatech.ca <mailto:perryd@athenatech.ca>
(403) 861-7556

**Comment by Devetzis** [comment]
Alex:

Oh, it it’s only the method name ‘county’ I have no problems with ‘sub_state’.


Perry Devetzis
Partner
Athena Technologies Corp.
perryd@athenatech.ca <mailto:perryd@athenatech.ca>
(403) 861-7556

**Comment by alexreisner** [comment]
OK, thanks for looking into this. Since it's mentioned in the API's docs I feel much better about it. Merging.

**Pull request merged**
