### PR TITLE
add PC Miler (Trimble) backend

### PR DESCRIPTION
**Pull request by alexdean**
Adds support for lookups via Trimble Maps.

  * API docs: https://developer.trimblemaps.com/restful-apis/location/single-search/single-search-api/
  * trial API key can be obtained here: https://developer.trimblemaps.com/get-an-api-key/na/

### CODE REVIEW

**Comment by alexdean** [comment]
@alexreisner : Marking this as a draft since I still need to write some tests & update the docs. I'm interested in any early feedback. Am I on the right track here? Any red flags?

**Comment by alexreisner** [comment]
Looking good so far! I'll comment in more detail when you're further along. No red flags. For handling the 403, you probably want to do something like this: https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/ipdata_co.rb#L53-L59

**Comment by alexdean** [comment]
@alexreisner ok i think this is ready to go. ready for a review whenever you've got time.

**Comment by alexdean** [comment]
@alexreisner maybe a flakey test here?

## in Github Actions

```
 Failure: test_results_without_street_address(TrimbleMapsTest)
/home/runner/work/geocoder/geocoder/test/unit/lookups/trimble_maps_test.rb:96:in `test_results_without_street_address'
     93: 
     94:     result = results[0]
     95: 
  => 96:     assert_equal '', result.street
     97:     assert_equal 'Duluth', result.city
     98:     assert_equal 'Minnesota', result.state
     99:     assert_equal 'MN', result.state_code
<""> expected but was
<"4 Pennsylvania Plaza">
```
https://github.com/alexreisner/geocoder/actions/runs/4968957710/jobs/8998451067?pr=1614#step:4:61

## locally for me

```
-> % git log | head -1
commit 676372e5957e9d3d35cf72ac8885737f4b0b7aff

-> % git status
On branch trimble_maps
nothing to commit, working tree clean

-> % rvm current
ruby-2.7.8

-> % bundle exec rake test
... lots of warnings omitted ...
Finished in 0.533754 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
575 tests, 3425 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1077.28 tests/s, 6416.81 assertions/s
```

## more info

if i understand the testing conventions in `geocoder`, the test that failed should be using the data from [test/fixtures/trimble_maps_duluth_mn](https://github.com/alexreisner/geocoder/blob/676372e5957e9d3d35cf72ac8885737f4b0b7aff/test/fixtures/trimble_maps_duluth_mn). editing the file locally & re-running tests confirms this. (Changes I make to that fixture file are visible in the unit test output.)

The string "4 Pennsylvania Plaza" occurs in many fixture files, so I can't tell where this one in particular came from, though [test/fixtures/trimble_maps_madison_square_garden](https://github.com/alexreisner/geocoder/blob/676372e5957e9d3d35cf72ac8885737f4b0b7aff/test/fixtures/trimble_maps_madison_square_garden) seems like a reasonable guess.

Any suggestions for how to troubleshoot this further? I don't understand what conditions could produce the test failure that I see in GH Actions.

**Comment by alexreisner** [comment]
Hmm, works locally for me too. I'm guessing this has to do with Github actions using a case-sensitive filesystem. I just pushed [d0ddb3a](https://github.com/alexreisner/geocoder/commit/d0ddb3a4f89b097ed58cb7ba4dad4aa4022e2464) which should fix it. Can you merge `master` into your branch (or rebase) and try again?

**Comment by alexreisner** [comment]
Thanks @alexdean, that did it. I'll take a look at the code shortly.

**Comment by alexdean** [comment]
@alexreisner heads up i just got a clarification from Trimble devs that this product is actually named PC Miler. (Trimble Maps is their map tile service...) Going to push a rename in just a minute. Wanted to save you the review time if you're looking at this soon.

**Comment by alexreisner** [comment]
@alexdean this looks great! I'm going to merge. Thanks for the clean, easy-to-review PR!

**Pull request merged**
