### PR TITLE
Warn people about minor breaking change

### PR DESCRIPTION
**Pull request by jaredbeck**
Per conversation in https://github.com/alexreisner/geocoder/pull/1103

[ci skip]

### CODE REVIEW

**Comment by alexreisner** [comment]
Thanks for this, but I just don't think it's necessary. This isn't really a breaking change, it just might affect the results of certain queries in a really tiny percentage of apps (ie, irrelevant to the vast majority of devs), and I think the minor version number increase is enough to alert people to that. It might be worth coming up with a way of indicating changes that could affect results, but I don't want to change the formatting of the CHANGELOG to do so (requires going back and updating for all previous releases), and honestly there are so many ways that changes affect apps that this is a bit of a rabbit hole. Eg: if a geocoding API is shut down and we remove it from Geocoder, is that a breaking change? More discussion on #1080.

**Comment by jaredbeck** [comment]
The goal here is to help people upgrade, by clarifying how likely a change is to cause them trouble. However we accomplish this is fine by me. Even a little parenthetical note at the end of the bullet point would be better than nothing, i.e. making no distinction at all between bullet points.

> What’s the point of a change log? To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project.
> http://keepachangelog.com/en/0.3.0/

The first bullet point is much more "notable" than the next three, isn't it?

Sorry for being persistent here, I'd just like to see a world where upgrading gems is easier :)

**Comment by alexreisner** [comment]
I hear you, and I want the same thing. It's just that this particular item is difficult to categorize. It's somewhere in between a breaking change and a totally innocuous one. And I think the note already in the CHANGELOG "(previously was sufficient to have only one of the two)" explains it pretty well. I'm not sure it's more notable than the other three items. For the vast majority of users it will have _less_ effect than the others.

Generally speaking, I don't include all changes in the CHANGELOG. The really minor stuff is omitted to encourage people to read and understand each item. If there were 10 items for each version then I could see more of a need for some kind of tagging, but as it stands I think the existing explanation for this item is alright. If a breaking change is introduced (the only ones so far have been dropping support for old Ruby/Rails) I'll tag with something in all caps.

**Comment by jaredbeck** [comment]
> It's just that this particular item is difficult to categorize.

Makes sense.

> Generally speaking, I don't include all changes in the CHANGELOG. The really minor stuff is omitted to encourage people to read and understand each item.

Yes! :+1::+1: That's great.

> If a breaking change is introduced (the only ones so far have been dropping support for old Ruby/Rails) I'll tag with something in all caps.

Awesome, thanks. I think we're on the same page :)

**Comment by alexreisner** [comment]
OK, great. And thanks again for this. Primary among my concerns for Geocoder are ease of installation and lack of surprise during use, so I consider this and #1080 to be issues worth discussing.

**Pull request closed without merging**
