### PR TITLE
Update ip2location lookup for v2 API

### PR DESCRIPTION
**Pull request by jamesbebbington**
Just a little PR to update the `ip2location` lookup to use [their v2 API](https://www.ip2location.com/web-service/ip2location).

### CODE REVIEW

**Comment by alexreisner** [comment]
Thanks for this! It looks good except I think the way you're merging params in `query_url_params`, `super` will overwrite the local config, which is the opposite of what we want. Can you take a look at that?

**Comment by jamesbebbington** [comment]
There you go, let me know if you want that commit squashed into previous.

**Comment by alexreisner** [comment]
Oof, thanks for pointing out Baidu. That's definitely wrong. And thanks for fixing! Will merge shortly.

**Comment by jamesbebbington** [comment]
Brilliant! Thanks Alex.

**Pull request merged**
