### PR TITLE
support for opencagedata optional parameters

### PR DESCRIPTION
**Pull request by stemps**
I added support for a bunch of optional opencage query parameters. Thought this could be interesting for other users as well. Feedback or suggestions are very welcome.

### CODE REVIEW

**Comment by alexreisner** [comment]
It's better to declare an array of symbols than to convert strings to symbols twice. Other than that, this looks good!

**Comment by stemps** [comment]
👍  good point! It's an array of symbols now.

**Comment by alexreisner** [comment]
Thanks! Unfortunately I think the `%I` shortcut was added in Ruby 2.0 and we still have to support 1.9.3 a little longer... Can you write it out the old fashioned way?

**Comment by stemps** [comment]
Ah... of course! I amended the commit.

**Pull request merged**
