### PR TITLE
Add syntax highlighting to README

### PR DESCRIPTION
**Pull request by thewatts**
Thanks for your amazing work on this gem!

### CODE REVIEW

**Comment by alexreisner** [comment]
Sorry, but please see #527, #624, #822, #993, #1234, #1424, #1486, etc.

**Comment by thewatts** [comment]
@alexreisner - 

Understandable. I apologize for not searching closed PRs first.

If I may make a suggestion or two:

It looks like, given now eight separate PRs suggesting the addition of syntax highlighting, that your userbase may tend to consume the documentation through GitHub's interface as opposed to the raw README file itself, and would find syntax highlighting helpful.

While the code examples are indeed simple (per your remarks with previous PRs), as someone new to the project - I personally find it easier to read and understand:

CleanShot 2021-06-28 at 17 13 01
 
vs

CleanShot 2021-06-28 at 17 13 37

---

Ultimately - it's not my call. And regardless of your decision - I still appreciate the joy that this project brings - thank you for your many years of hard work on it.

**Comment by alexreisner** [comment]
OK, I think you've finally changed my mind on this. Thanks for your patience and thoughtful explanation. Will merge.

**Comment by thewatts** [comment]
Thank you, @alexreisner !

**Pull request merged**
