### PR TITLE
Add Mapzen reverse geocoding

### LINKED ISSUE #1039: Mapzen reverse geocoding param error
With version 1.3.4 of **geocoder**, when trying to perform a reverse geocode using **:mapzen** as lookup engine, it returns a 400 error.

Inspecting the created URL, the coordinates are included in a `text` parameter:

https://search.mapzen.com/v1/reverse?api_key=search-xxx&size=1&text=[39.57,+-0.48]

This request returns the following error:

> _parameters point.lat and point.lon must both be specified_

According to [Mapzen docs](https://mapzen.com/documentation/search/reverse/), it should be set as separated `point.lat` and `point.lon` parameters:

https://search.mapzen.com/v1/reverse?api_key=search-xxx&size=1&point.lat=39.57&point.lon=-0.48

### PR DESCRIPTION
**Pull request by shinyaK14**
I  implemented Mapzen reverse geocoding.

To resolve #1039 Mapzen reverse geocoding param error.

Thanks.

### CODE REVIEW

**Comment by alexreisner** [comment]
Thanks! This code looks good but I think it should be added on the `:pelias` lookup rather than `:mapzen` (?).

**Comment by shinyaK14** [comment]
@alexreisner Yes, I agree. I moved Mapzen reverse geocoding to Pelias.
The code is much better. Thanks!!

**Comment by alexreisner** [comment]
OK, great. This looks good. My only other question is: why are we limiting to HTTPS? It seems like someone might want to configure an endpoint that doesn't support SSL.

**Comment by shinyaK14** [comment]
@alexreisner The reason is that I couldn't find Mapzen supports http protocol in their document. 
But yeah. We should NOT limit it. In case someone want to configure as http.

**Comment by alexreisner** [comment]
OK, thanks. One last thing: I think the test should be on the Pelias lookup as well, since Mapzen inherits from Pelias and that's where the reverse geocoding was implemented.

If that makes sense, please also squash all of the above into a single commit and I'll merge. Thanks!

**Comment by alexreisner** [comment]
OK, thanks. One last thing: I think the test should be on the Pelias lookup as well, since Mapzen inherits from Pelias and that's where the reverse geocoding was implemented.

If that makes sense, please also squash all of the above into a single commit and I'll merge. Thanks!

**Comment by alexreisner** [comment]
OK, thanks. One last thing: I think the test should be on the Pelias lookup as well, since Mapzen inherits from Pelias and that's where the reverse geocoding was implemented.

If that makes sense, please also squash all of the above into a single commit and I'll merge. Thanks!

**Comment by alexreisner** [comment]
OK, thanks. One last thing: I think the test should be on the Pelias lookup as well, since Mapzen inherits from Pelias and that's where the reverse geocoding was implemented.

If that makes sense, please also squash all of the above into a single commit and I'll merge. Thanks!

**Comment by shinyaK14** [comment]
@alexreisner Thanks for your advice. I really appreciate it!!
I'm a big fan of Geocoder :)

**Comment by alexreisner** [comment]
Thank **you** for the contribution!

**Pull request merged**
